<a href="https://colab.research.google.com/github/nuhaminmengiste/HarvardX_Using_Python_for_Research/blob/master/Using_Python_for_Research_Homework_Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using Python for Research Homework: Week 2

In this homework, we will use the tools we've covered in the past two weeks to create a tic-tac-toe (noughts and crosses) simulator and evaluate basic winning strategies.

### Exercise 1

Tic-tac-toe (or noughts and crosses) is a simple strategy game in which two players take turns placing a mark on a 3x3 board, attempting to make a row, column, or diagonal of three with their mark. In this homework, we will use the tools we've covered in the past two weeks to create a tic-tac-toe simulator and evaluate basic winning strategies.

In the following exercises, we will learn to create a tic-tac-toe board, place markers on the board, evaluate if either player has won, and use this to simulate two basic strategies.

#### Instructions 

- For our tic-tac-toe board, we will use a numpy array with dimension 3 by 3. 
- Make a function `create_board()` that creates such a board with the value of each cell set to the integer `0`.
- Call `create_board()` and store it.

In [312]:
import numpy as np
def create_board():
    x = np.zeros((3,3), dtype=int)
    return x
create_board()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Exercise 2

Players 1 and 2 will take turns changing values of this array from a 0 to a 1 or 2, indicating the number of the player who places a marker there.

#### Instructions 

- Create a function `place(board, player, position)`, where:
    - `player` is the current player (an integer 1 or 2).
    - `position` is a tuple of length 2 specifying a desired location to place their marker.
    - Your function should only allow the current player to place a marker on the board (change the board position to their number) if that position is empty (zero).
- Use `create_board()` to store a board as `board`, and use `place` to have Player 1 place a marker on location `(0, 0)`.

In [318]:
#defining our function
def place(board, player, position):
    #specifying the parameters
    #player == 1 or 2 how to make players parameter 1 or 2??????
    x,y = position
    #making sure player checks of position is open AND that one of the players then marks it
    if board[position] == 0:
        board[position] = player
    return board
#storing board as create_board and making player 1 make her mark on position (0,0)
board = create_board() 
#setting the arguments of the place
place(board, 1, (0,0))
#checking if board matrix has changed its value
board

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Exercise 3

In this exercise, we will determine which positions are available to either player for placing their marker.

#### Instructions 
- Create a function `possibilities(board)` that returns a list of all positions (tuples) on the board that are not occupied (0). (Hint: `numpy.where` is a handy function that returns a list of indices that meet a condition.)
- `board` is already defined from previous exercises. Call `possibilities(board)` to see what it returns!

In [319]:
def possibilities(board):
    #setting the index nubmer
    x = [0, 1, 2]
    y = [0, 1, 2]
    #creating an array of x values (shown in row 1) and corresponding y values (shown in row 2) that meet the condition set
    a = np.where(board == 0)
    #packing the x and y values of rows 0 and 1 respectively as tuples for convenience when indexing
    possible = []
    print(len(a), len(a[0]))
    for i in range(len(a[0])):
       possible.append([a[0][i],a[1][i]])
    return np.array(possible)
#returns an array of possibilities where first row [0] is the x values and second row [1] are the corresponding y values
possibilities(board)
#check out https://thispointer.com/find-the-index-of-a-value-in-numpy-array/ "Find index of a value in 2D Numpy array | Matrix"
#restructuring the result to make it an array of tuples

2 8


array([[0, 1],
       [0, 2],
       [1, 0],
       [1, 1],
       [1, 2],
       [2, 0],
       [2, 1],
       [2, 2]])

### Exercise 4

The next step is for the current player to place a marker among the available positions. In this exercise, we will select an available board position at random and place a marker there.

#### Instructions 

- Write a function `random_place(board, player)` that places a marker for the current player at random among all the available positions (those currently set to 0).
    - Find possible placements with `possibilities(board)`.
    - Select one possible placement at random using `random.choice(selection)`.
- `board` is already defined from previous exercises. Call `random_place(board, player)` to place a random marker for Player 2, and store this as board to update its value.

In [320]:
#defining the function
import random 
random.seed(1)
def random_place(board,player):
    #making sure to randomly select values from row 1 (x-values) and then select its corresponding y-value when indexing baord, b/c selecting both of them at random risks selecting board positions that are already filled
    x = (random.choice(possibilities(board)))
    #print(x)
    #print(x[0])
    #print(x[1])
    board[x[0],x[1]] = player
    return board
#randomly marking an open position with player 2
random_place(board,2)
#checking the possiblities left
#possibilities(board)

2 8


array([[1, 0, 0],
       [2, 0, 0],
       [0, 0, 0]])

### Exercise 5

We will now have both players place three markers each.

#### Instructions 

- A new `board` is already given. Call `random_place(board, player)` to place three pieces each on board for players 1 and 2.
- Print board to see your result.

In [321]:
random.seed(1)
board = create_board()
for i in range(3):
  random_place(board,1)
  random_place(board,2)
print(board)


2 9
2 8
2 7
2 6
2 5
2 4
[[2 2 1]
 [0 1 0]
 [0 1 2]]


### Exercise 6

In the next few exercises, we will make functions that check whether either player has won the game.

#### Instructions 
- Make a function `row_win(board, player)` that takes the player (integer) and determines if any row consists of only their marker. 
    - Have it return `True` if this condition is met and `False` otherwise.
- `board` is already defined from previous exercises. Call `row_win` to check if Player 1 has a complete row.

In [322]:
def row_win(board,player):
  for i in range(len(board)):
    if np.all(board[i]==player):
      return True
  return False
print(row_win(board, 2))


False


### Exercise 7

In the next few exercises, we will make functions that verify if either player has won the game.

#### Instructions 
- Make a function `col_win(board, player)` that takes the player (integer) and determines if any column consists of only their marker. 
    - Have it return `True` if this condition is met and `False` otherwise.
- `board` is already defined from previous exercises. Call `col_win` to check if Player 1 has a complete row.

In [323]:
def col_win(board,player):
  for i in range(3):
    if np.all(board[:,i]==player):
      return True
  return False
print(col_win(board, 2))


False


### Exercise 8

In the next few exercises, we will make functions that verify if either player has won the game.

#### Instructions 
- Finally, create a function `diag_win(board, player)` that tests if either diagonal of the board consists of only their marker. Have it return `True` if this condition is met, and `False` otherwise.
- `board` has been slightly modified from a previous exercise. Call `diag_win` to check if Player 2 has a complete diagonal.

In [324]:
board[1,1] = 2
def diag_win(board,player):
  a = np.all(np.diagonal(board)==player)
  b = np.all(np.fliplr(board).diagonal()==player)
  if a == True or b == True:
    return True
  return False
print(diag_win(board, 2))

True


### Exercise 9

In the next few exercises, we will make functions that check whether either player has won the game.

#### Instructions 
- Create a function `evaluate(board)` that uses `row_win`, `col_win`, and `diag_win` functions for both players. If one of them has won, return that player's number. If the board is full but no one has won, return -1. Otherwise, return 0.
- `board` is already defined from previous exercises. Call evaluate to see if either player has won the game yet.

In [326]:
def evaluate(board):
    for player in [1, 2]:
      winning = np.array([diag_win(board,player), col_win(board,player), row_win(board,player)], dtype= bool)
      print("winning ", winning)
      if np.any(winning == True):
          return player

    if np.all(board != 0):
      return -1 

    return 0
evaluate(board)

winning  [False False False]
winning  [ True False False]


2

### Exercise 10

In this exercise, we will use all the functions we have made to simulate an entire game.

#### Instructions 

- `create_board()`, `random_place(board, player)`, and `evaluate(board)` have been created in previous exercises. Create a function `play_game()` that:
    - Creates a board.
    - Alternates taking turns between two players (beginning with Player 1), placing a marker during each turn.
    - Evaluates the board for a winner after each placement.
    - Continues the game until one player wins (returning 1 or 2 to reflect the winning player), or the game is a draw (returning -1).
- Call play_game 1000 times, and store the results of the game in a list called `results`.

In [337]:
#defining the function
random.seed(1)
def play_game():
  board = create_board()
  player = 1
  while np.any(board == 0):
    random_place(board,player)
    if evaluate(board) == player:
      return player
    else:
      if player == 1:
        player = 2
      else:
        player = 1
  return evaluate(board)
print(play_game())

#Playing the game 1000 times
results = []
for i in range(1000):
  a = play_game()
  results.append(a)
print(results) 

#counting the number of times player 1 has won
play_1 = 0
for i in range(len(results)):
  if results[i]==1:
    play_1 += 1
play_1


Streaming output truncated to the last 5000 lines.
winning  [False False False]
winning  [False False False]
2 7
winning  [False False False]
winning  [False False False]
2 6
winning  [False False False]
winning  [False False False]
2 5
winning  [False False False]
winning  [False False False]
2 4
winning  [False False False]
winning  [False False  True]
2 9
winning  [False False False]
winning  [False False False]
2 8
winning  [False False False]
winning  [False False False]
2 7
winning  [False False False]
winning  [False False False]
2 6
winning  [False False False]
winning  [False False False]
2 5
winning  [False False False]
winning  [False False False]
2 4
winning  [False False False]
winning  [False False False]
2 3
winning  [False False False]
winning  [False False False]
2 2
winning  [False False False]
winning  [False False False]
2 1
winning  [False False False]
winning  [False False False]
winning  [False False False]
winning  [False False False]
2 9
winning  [False False F

591

#### Exercise 11

In the previous exercise, we see that when guessing at random, it's better to go first, as expected. Let's see if Player 1 can improve their strategy. 

#### Instructions 
- Create a function `play_strategic_game()`, where Player 1 always starts with the middle square, and otherwise both players place their markers randomly.
- Call `play_strategic_game` 1000 times.

In [339]:
random.seed(1)
def play_strategic_game():
  #player 1 placing in the middle
  board = create_board()
  place(board,1,(1,1))
  #random placements by each players
  player = 2
  while np.any(board == 0):
    random_place(board,player)
    if evaluate(board) == player:
      return player
    else:
      if player == 2:
        player = 1
      else:
        player = 2

  return evaluate(board)
print(play_strategic_game())
board

#running the code 1000 times
results_second = []
for i in range(1000):
  a = play_strategic_game()
  results_second.append(a)
print(results_second) 

#counting the number of times player 1 has won
play_1_strategic = 0
for i in range(len(results_second)):
  if results_second[i]==1:
    play_1_strategic += 1
play_1_strategic


Streaming output truncated to the last 5000 lines.
winning  [ True False False]
2 8
winning  [False False False]
winning  [False False False]
2 7
winning  [False False False]
winning  [False False False]
2 6
winning  [False False False]
winning  [False False False]
2 5
winning  [False False False]
winning  [False False False]
2 4
winning  [False False False]
winning  [False False False]
2 3
winning  [False False False]
winning  [False False False]
2 2
winning  [False False False]
winning  [False False False]
2 1
winning  [False False  True]
2 8
winning  [False False False]
winning  [False False False]
2 7
winning  [False False False]
winning  [False False False]
2 6
winning  [False False False]
winning  [False False False]
2 5
winning  [False False False]
winning  [False False False]
2 4
winning  [False False False]
winning  [False False False]
2 3
winning  [False False False]
winning  [False False False]
2 2
winning  [False False False]
winning  [False False False]
2 1
winning  [False

717